### ISSUE TITLE
bootstrap fails when building Trilinos

### ISSUE THREAD

**Issue by raovgarimella** [amanzi/amanzi#118]
When I try to build Amanzi using bootstrap, building of Trilinos fails with 
CMake Error at trilinos-timestamps/verify-trilinos.cmake:27 (message):
  error: MD5 hash of

    /home/rao/develop/amanzi/build/build/tpls/Downloads/trilinos-release-12-10-1
.tar.gz

  does not match expected value

    expected: 40f28628b63310f9bd17c26d9ebe32b1
      actual: 667333dbd7c0f031d47d7c5511fd0810

CMake Error at trilinos-timestamps/trilinos-download-Release-impl.cmake:19 (mess
age):
  Command failed (1):

Ubuntu 16.04

**Comment by ekikinzon** [comment]
Had a similar problem on Wolf, and I think it was because of xSDK. When building on my MacBook, xSDK wasn't dowloaded and everything built without issues. On Wolf, though, it needed xsdk and then complained about the checksum. Specifically, 

set(HYPRE_ARCHIVE_FILE   xsdk-${XSDK_VERSION}.tar.gz)
set(HYPRE_SAVEAS_FILE    hypre-${HYPRE_VERSION}.tar.gz)
set(HYPRE_MD5_SUM        fc9474058560602e9be2ce618db7fd14)

instead of the checksum of hypre above, it was computing the checksum of xsdk, which obviously didn't match.

**Comment by lipnikov** [comment]
Trillions checksum changed externally. It was changed to 667333... the last week in our scripts.

**Comment by lipnikov** [comment]
Stand-alone build.
I provided SAVEAS_FILE option to all TPLs. Looks like PETSc now needs a text process package sowing. Configuration fails without it. Any suggestions.

**Comment by raovgarimella** [comment]
Verified that it works on Ubuntu 16.04
