### ISSUE TITLE
Amanzi map

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#264]
Implement class Amanzi_Map. This will be a derived class from Epatra_Map. At the moment it will keep a RCP pointer to the unstructured mesh-free Epetra_Map and  the integer mesh-based Epetra_Vector containing pointers to the first DOF in the unstructured map.

**Comment by ecoon** [comment]
Huh?  What is the "first DOF in the unstructured map"?  What is a DOF of a mesh?  What role is this supposed to fill?

**Comment by dasvyat** [comment]
This map is unstructured, in a sense, or maybe more correctly to describe it as nonuniform, which allows one to define different number of dofs on different mesh entities. Right now, it is already implemented the interface to create CompositeVectors and CompositeVectorSpaces based on master and ghost mappings with or without reference to a particular mesh location. In order to use nonuniform maps a more complex mapping class is required.  The one which able to find a particular segment of global mapping which corresponds to a local entity or pointer the first dof on this entity.

**Comment by ecoon** [comment]
I would start by looking into Epetra_BlockMap.  I think this is what you want.

https://trilinos.org/docs/dev/packages/epetra/doc/html/classEpetra__BlockMap.html#a911491bf44f662dfba5f74c804480a42

**Comment by lipnikov** [comment]
This is confusing: "More generally, an element in the BlockMap class is an ordered list of points. (NOTE: Points do not have global ID's.)" . Hence, we still need to convert variable-size BlockMap to a flat map to be used in our matrix assembly routines.

**Comment by lipnikov** [comment]
Clear. Thanks a lot. Looks like the design of VbrMatrix was inspired by high-order DG methods. In our use case, we have 2 DOFs on faces living on manifolds and 1 DOF on the other faces, so almost everywhere we have 1 DOF. We will have to create a flat Epetra_Map.

**Comment by lipnikov** [comment]
After talking to Daniil... To avoid additional class, we can try to switch from Epetra_Map to Epetra_BlockMap  in CompositeVectorSpace and rewrite SuperMap to handle both uniform and non-uniform maps.
