### ISSUE TITLE
State times have no default values

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#294]
Either cycle driver or state should initialize state times such as intermediate_time_, initial_time_, final_time_, etc. The implication is that a PK cannot run AdvanceStep() outside of cycle driver.

**Comment by ecoon** [comment]
I'm not sure I understand.  Do you just want them to be initialized to 0 so they are not undefined?  Or do you want them initialized to a user-provided value outside of cycle driver, and if so, who should provide those times?

**Comment by lipnikov** [comment]
I do not have a solution.

**Comment by ecoon** [comment]
Haha, I'm not sure what the problem is.  You want to use a PK without cycle driver?  How do you know how far to AdvanceStep()?  The PK doesn't call AdvanceStep() itself, someone has to.  That someone (whether cycle driver or something else) should initialize State as well to be consistent with what it is going to call AdvanceStep() starting at.  State is not self-contained within a PK.

Doesn't Amanzi's cycle driver initialize the times?  Or who does in the standard amanzi executable?

**Comment by lipnikov** [comment]
Okay, it is easier to type with a keyboard at hand ;-). The use of AdvanceStep is useful for unit tests to reduce amount of a high-level management.  Currently, all times are set inside a test. It is a feasible approach but requires a few lines of unrelated (at first glance) code.

**Comment by lipnikov** [comment]
set_xxx_time() functions are available in State. They should be used in unit tests.
