### ISSUE TITLE
bootstrap confusion over TPL version

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#375]
See the attached output from bootstrap, tpl_version.h, and amanzi-tpl-config.cmake, which included a full installation of both TPLs and Amanzi.

All installed as expected, and tpl_version.h and amanzi-tpl-config.cmake seem to think I installed TPLs version 0.96.3.

But AmanziTPL.cmake seems to think I have version 0.95.5 installed, and warns about this...

[tpl_versions.h.txt](https://github.com/amanzi/amanzi/files/3922344/tpl_versions.h.txt)
[amanzi-tpl-config.cmake.txt](https://github.com/amanzi/amanzi/files/3922345/amanzi-tpl-config.cmake.txt)
[bootstrap_out.log](https://github.com/amanzi/amanzi/files/3922341/bootstrap_out.log)

**Comment by ecoon** [comment]
This has got to be some kind of server problem with slow hard drive access or something?  It looks fairly clear that Amanzi's CMakeLists.txt picks AMANZI_TPLS_VERSION from amanzi-tpl-config.cmake, so it can't be 0.95.5 if that is the file being read...

**Comment by jd-moulton** [comment]
The goal is to give the user/developer a check on versions between the TPLs that were installed and the expected version for source code that is being built. It's only a warning because developers could be playing around or knowingly testing different versions.

The version information for what was installed comes from the cache stored in the file 

`${TPL_INSTALL_PREFIX}/config/share/amanzi-tpl-config.cmake`

and the version is in `AMANZI_TPLS_VERSION`. The code in AmanziTPL.cmake reports this value, but does not compute it. 

The version information for the source code is extracted from the file 

`${CMAKE_SOURCE_DIR}/config/SuperBuild/TPLVersions.cmake`

by some string processing code in AmanziTPL.cmake, and it reports that as the "required" version, although "required" isn't enforced (as noted above).

So if you were building and overwriting a previous installation, I could see where some strangeness could happen with cached files and lazy server writes.  If you were installing into an empty or new directory I'm not sure how these checks could go wrong.

**Comment by ecoon** [comment]
Yeah, I think it must be your last comment.  If I extract the configure command from bootstrap and copy/paste it into the terminal and run it explicitly, it picks up the correct version numbers.

**Comment by lipnikov** [comment]
This is due to presence of old version of amanzi in build/amanzi. I am closing the ticket since I noticed the same behavior. It was resolved by erasing build/amanzi
