### ISSUE TITLE
TreeOperator of TreeOperators

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#453]
The current concept of the TreeOperator is not easy to extend to a hierarchical case when a TreeOperator of TreeOperators is needed.  One problem is Apply(x, y) where x and y are some TreeVectors. For a hierarchical implementation, we need to switch to the CV and Operator interfaces, which is feasible but not so great implementation-wise.  Do you see any alternatives?

**Comment by ecoon** [comment]
I'm not sure I understand what aspect of the CV and Operator interfaces you're looking for.  Is it just the double optional argument to Operator::Apply?  That seems straightforward.

I agree that this doesn't deal with being hierarchical right now because SetOperatorBlock() and its other block stuff is all Operators instead of recursively TreeOperators.  Is that the problem?

**Comment by lipnikov** [comment]
From the comment section: "Note that a TreeVector may have EITHER subvecs OR data..." Thus, we need to fork the code to use different data access, and either TreeOperator::Apply(TV, TV) or Operator::Apply(CV, CV).

**Comment by lipnikov** [comment]
SetOperatorBlock() could be used for an approach alternative to a hierarchical approach. But it requires tools like RCP<TV> to std::vector<RCP<CV>> conversion. I want to discuss options before writing more code.

**Comment by ecoon** [comment]
> From the comment section: "Note that a TreeVector may have EITHER subvecs OR data..." Thus, we need to fork the code to use different data access, and either TreeOperator::Apply(TV, TV) or Operator::Apply(CV, CV).

There does need to be a fork, but the interface is consistent -- TreeOperator::Apply only accepts TreeVectors.  If both the domain and range are leaf nodes, then the TreeOperator has a non-null RCP<Operator>, and implements Apply by calling Operator::Apply().  If either domain or range are not leaf nodes, then it has a size(domain) x size(range) 2D array of TreeOperators, which may themselves either be leaf or internal nodes, where size() is defined by:

```
int size(TVS tvs) {
    int s = tvs.NumChildren();
    if (tvs.Data() != null) s++;
    return s;
}
```

Whenever a domain (or range) is a leaf but the other is not, then the domain (respectively range) of those children TreeOperators is the same as this's domain (respectively range).  See the attached image of 4 examples, where orange implies leaf and brown implies internal node (where leaf in the case of operators means _both_ domain and range are leaves).  Note that the subgraph rooted at the left child in the 4th example is the same as the 2nd example -- the "inner" brown box in the operator representation can be handed off to an MPC/etc who will see an identical representation and interface as if it were the MPC at example 2 who knew nothing about the fact that it was coupled.

![Unknown](https://user-images.githubusercontent.com/5126139/86160867-6d714c80-bada-11ea-969d-8729422f6d80.jpeg)

Note that supermap and other things that want to just look at the "flattened" version of this e.g. a 2D array of leaves can use depth-first searches to iterate over all leaf nodes (this is implemented in TreeVector_Utils).

**Comment by ecoon** [comment]
>  But it requires tools like RCP to std::vector<RCP> conversion.

What do you mean by this?  Sure, we need a 2D array of RCPs of TreeOperators, in the same way TreeVector has a 1D array of RCPs of TreeVectors for its children.  This is most easily done with std::vector, but could be done with a simpler 2D array class if there was one (that wasn't std::array as that is compile-time).

**Comment by lipnikov** [comment]
> What do you mean by this?

I mean that it is possible to avoid adding a 2D array of TreeOperators by flattening a TreeOperator inside each MPC PK.

**Comment by ecoon** [comment]
> > What do you mean by this?
> 
> I mean that it is possible to avoid adding a 2D array of TreeOperators by flattening a TreeOperator inside each MPC PK.

Do you mean flattening it and storing a 2D array of Operators?  Or "unraveling" it and storing a 1D array of TreeOperators?  I'm guessing you mean the 1st?

If so, my concern is that we have to be able to present a sub-MPC (e.g. an MPC that is itself coupled by another MPC) with a self-consistent TreeOperator.  It may be filled at this lower level, then assembled at the higher level.  To me the recursive design feels less buggy than having to worry about the consistency of two representations storing pointers to the same thing.  For instance, what if SetBlock() gets called at the lower level's TreeOperator -- then then parent's pointer is still null unless the vectors are non-owning views that share the same memory (which is not possible with std::vector as far as I know, but would be possible with Teuchos::ArrayView).  I considered this when writing TreeVector (the question is the same... I could have flattened TV's children into a single std::vector<CompositeVector>), but it seemed less complicated to recurse.

Note that if you want to flatten, I would suggest that TreeVector also get rewritten as a flattened version so that they follow the same design. I think this is more complicated, and don't think it adds value relative to the existing recursive implementation.

For what it is worth, I don't think changing the TreeOperator with the proposed recursive implementation is much work.  Basically just requires updating the blocks to TreeOperators themselves and adding a few conditionals in the Apply methods.  If you'd like to design some tests, I'd be happy to implement and we could make sure the implementation does what your use cases.

**Comment by lipnikov** [comment]
For compatibility, I would make data_ as a 2D array of Operators.

**Comment by dasvyat** [comment]
If TreeOperator on each level would have access to  2D array of  Operators that define its structure will it violate any underlining principles? This 2D array can be constructed recursively.

**Comment by ecoon** [comment]
> Does collectTreeVectorLeaves(TV) preserve the implicit tree order defined by the input TV?

yes



> If TreeOperator on each level would have access to 2D array of Operators that define its structure will it violate any underlining principles? This 2D array can be constructed recursively.

The difficult part is making sure that the 2D array of Operators at one level is the _same memory_ as a subset of the 2D array of memory at the higher level.  It must be the same memory, and not a copy of that memory, because otherwise a child could change the pointer, and not know how to tell the parent that it has done so.

**Comment by ecoon** [comment]
> Does collectTreeVectorLeaves(TV) preserve the implicit tree order defined by the input TV?

yes


> If TreeOperator on each level would have access to 2D array of Operators that define its structure will it violate any underlining principles? This 2D array can be constructed recursively.

The difficult part is making sure that the 2D array of Operators at one level is the _same memory_ as a subset of the 2D array of memory at the higher level.  It must be the same memory, and not a copy of that memory, because otherwise a child could change the pointer, and not know how to tell the parent that it has done so.

**Comment by ecoon** [comment]
I'm working on a refactor of LinearOperator and Preconditioner for the Tpetra branch -- we made some bad assumptions there I think (for instance that these were fundamentally different somehow, I think we justified this by saying that preconditioners were assembled by linear operators weren't) which we promptly broke by adding things like LinearOperatorAmesos (which needs an assembled thing) and PreconditionerDiagonal (doesn't need an assembled thing).

Let me stop and do that refactor on a branch of master instead of a branch of tpetra.  This will make it easier to do the Tree work as well.  Will open a ticket and branch for that.

**Comment by dasvyat** [comment]
> The difficult part is making sure that the 2D array of Operators at one level is the _same memory_ as a subset of the 2D array of memory at the higher level. It must be the same memory, and not a copy of that memory, because otherwise a child could change the pointer, and not know how to tell the parent that it has done so.

If it is an array of RCP pointers what is the issue of the same memory? Also, TreeOperator probably doesn't need to have a write access for Operators.

**Comment by lipnikov** [comment]
> broke by adding things like LinearOperatorAmesos (which needs an assembled thing) and PreconditionerDiagonal (doesn't need an assembled thing).

right ;-) Just like calling PCG a linear operator. I would rename all to be correct with what we know from linear algebra.

**Comment by ecoon** [comment]
Ok, so I think this is either working or close to working, but we need to discuss how PKs fill this object before I go further into testing.

In both Amanzi and ATS, PKs that implement the BDF interface are required to supply a method:

```
    Teuchos::RCP<Operator> preconditioner();  // ATS variant, in pk_bdf_physical_default
    Teuchos::RCP<Operator> my_operator(); // Amanzi variant, in PK_BDF.hh
```

that returns the global operator for that PK.  This allows an MPC to shove the resulting Operator into the TreeOperator via `set_operator_block()`.  This enables the diagonal block to be set up, managed, etc by the owning PK, which knows all about that physics.  Then the MPC may additionally set off-diagonal blocks (e.g. in ATS, we do this in mpc_subsurface.cc, while in Amanzi, this is done in at least operators/test/operator_stokes.cc).

This works great for the "flat, single level" TreeOperator, but won't work in the 2-level case.  For a canonical 2-level case, let's consider the case of surface + subsurface, flow + energy (or equivalently fracture + matrix, flow + energy).  In both of these cases, we have implemented flat versions of MPCs to work around the issue of needing a 2-level TreeOperator, whereby a flow+energy MPC (surface, fracture) is coupled to another flow+energy MPC (subsurface).  

In that (global implicit) case, the matrix must be assembled at the highest level, so we need a TreeOperator of 2x2 TreeOperators, each of which are 2x2 "leaf" TreeOperators.

To assemble this thing, I would suggest the following interface:

`Teuchos::RCP<TreeOperator> PK_BDF::get_preconditioner();`

I call it "get_preconditioner()" because it is the linearization created in `PK_BDF::UpdatePreconditioner()` and applied in `PK_BDF::ApplyPreconditioner()`, not because it is approximate -- it may in fact be the true Jacobian.  I would be willing to call this `PK_BDF::get_Jacobian()` or similar, but then I would suggest changing the BDF interface as well to match (e.g. `PK_BDF::UpdateJacobian()`, `PK_BDF::ApplyInverseJacobian()` or something similar.

Then, instead of using `my_operator()` or similar, the mid-level (e.g. Flow+Energy on the subsurface) MPC would call subsurface flow's `get_preconditioner()` and shove it into its own 2x2 TreeOperator via something like:

```
global_tree_op_->set_block(pks_[0]->get_preconditioner(), 0,0);
global_tree_op_->set_block(pks_[1]->get_preconditioner(), 1,1);

// additionally, do something for off-diagonal block....
// like what if k_rel is a function of T?  Then we want dk/dT terms!
PDE_Diffusion dflow_dT_block = ....
global_tree_op_->set_block(dflow_dT_block.global_operator(), 0, 1);

// similar for dEnergy_dp...
```

Then, after this is done (in that MPC's UpdatePreconditioner method), the "top level" MPC can make its own global preconditioner...

```
global_tree_op_->set_block(pks_[0]->get_preconditioner(), 0,0);  // This is now the flow + energy subsurface 2x2 block
global_tree_op_->set_block(pks_[1]->get_preconditioner(), 1,1);  // This is now the flow + energy fracture/surface 2x2 block

// get derivatives of the coupling term between subsurface and fracture
PDE_Accumulation dFlowSubsurface_dpFracture = ....
PDE_Accumulation dEnergySubsurface_dTFracture = ...

// shove them in a new block, which is necessarily not square!
// .. create maps....
Teuchos::RCP<TreeOperator> tree_op_01 = Teuchos::rcp(new TreeOperator(row_map, col_map));
tree_op_01->set_block_operator(dFlowSubsurface_dpFracture.global_operator(), 0,0);
tree_op_01->set_block_operator(dEnergySubsurface_dTFracture.global_operator(), 1,1);

// now stick THAT thing in the global op...
global_tree_op_->set_block(tree_op_01, 0, 1);


// finally we can assemble this whole thing into a flat supermap in the usual way
global_tree_op_->set_inverse_parameters(my_boomer_amg_parameterlist);
...
```

Thoughts or comments?  Other ways of doing this?  Preferred names?

**Comment by lipnikov** [comment]
(1) PK may potentially provide two operators matrix and preconditioned, see my_operator(OperatorType) in Amanzi's.
I'm flexible with names but I want a richer interface to a PK.
(2) I prefer a cloning mechanisms behind set_block(), so that additional operators added by MPC to the global operators in the TreeOperator matrix will be added to the clone only, and the lower-level PK will not see them. Example is matrix-fracture fluxes that modify diagonal and off-diagonal operators. BTW, how do u handle coupling physics in ATS? In Amanzi, it is handled by both MPC and PKs depending on a time integrator.
(3) Interface that would allow us to insert a TreeOperator not aligned with the box-structure of the global TreeOperator. I do not have a clear example, something related to approximation of a physics-aware Schur complement that make sense only on the level of MPC, a-la  div \Laplace^-1 \grad in Stokes for pressure block, but in the Stokes, it is aligned with the box structure of the TreeOperator.

**Comment by ecoon** [comment]
1, sounds good.
3, I'm not sure there is any restriction to this now.  As long as you make sure to keep the row/range and column/domain maps consistent with the TreeOperator, everything should be fine.  Filling off-diagonals in that case might be a bit tricky, but presumably the MPC that does this knows what to do.

2 may be tricky.  What exactly gets cloned?  Just the TreeOperator?  The TreeOperator + the Operator?  The TreeOperator + Operator + contained Op local matrices? 

If the last, then you have to reconstruct everything any time the PK changes the values of the Op.  That seems like a huge inefficiency.  Maybe one could clone the TreeOperator or the TreeOperator + the Operator without too much inefficiency.

At some level, this is entirely up to the MPC implementer -- they can choose to do any of these, but the choices have implications on performance and bookkeeping.  I'm happy to add a clone to the TreeOperator that calls Operator's clone, which I think you implemented so presumably does what you want it to do?

This would not be an issue in ATS because an MPC would not add to the diagonal operator.  In ATS, coupling physics is handled in two places.  The residual isn't touched by the MPC, so all terms in the residual are dealt with in the PK.  

The Jacobian is handled in two places, the PK for derivatives with respect to the primary variable and the MPC for derivatives with respect to other (off-diagonal) variables.  Because ATS uses the DAG for source terms, the matrix source would be updated to include coupling fluxes in the DAG, and the derivatives/chain rule/etc would be done via the DAG, and so dQ/dp would include dQ_{fracture-matrix exchange flux}/dp.  So in the fracture-matrix coupling flux case, the PK would get the exchange flux in its source, derivatives of that with respect to p_matrix would go into the PK (with no additional work, it naturally is done in the DAG), and the derivatives of flow's source with respect to p_fracture would get dealt with by the MPC (who controls the off-diagonal block).  This is necessary because the matrix flow PK has no knowledge of a p_fracture in any way.

**Comment by lipnikov** [comment]
2. I think cloning of TreeOperator that calls cloning of Operators is sufficient.

**Comment by ecoon** [comment]
Ok, adding that now.  To be clear, I don't want set_block() to clone, because ATS will not make copies.  But I will add a TreeOperator copy constructor which does a deep copy, and a clone() which calls it.

I'm willing to add a set_block_clone() method if you'd like it, but it would just be shorthand for:

```
void set_block_clone(int i, int j, const Teuchos::RCP<TreeOperator> block) {
    set_block(i, j, block->Clone());
}
```

which isn't obvious to me that it saves any thought.  Alternatively, you could always implement your PKs to have get_operator() / get_preconditioner() return clones (though this forces the clone always, maybe you don't want that).

**Comment by lipnikov** [comment]
What is cloned in Operator is the global_operator pointer. Looks like it implies delegation for a TreeOperator, like in your code snapshot.

**Comment by ecoon** [comment]
Looking at the Operator_* objects, I don't see that they actually implement a copy constructor, but they call it in their clone (e.g. https://github.com/amanzi/amanzi/blob/master/src/operators/Operator_Cell.cc#L221 ) which means they do a shallow copy.  

But that makes sense -- you effectively want a shallow copy which implies a new vector of local ops.  So you can then add to that vector and not affect the original Operator object.  So I think calling `set_block(I,j,block->Clone())`, or `set_operator_block(i,j,block->Clone())` should do exactly what you want, e.g make a new operator that you can add things to without affecting the PK's version of the Operator.  

I'll open a pull request for this now to make things easier to review.  Obviously I haven't touched any PKs, and the only one that could be updated (but still works as-is) is the coupled Energy + Flow matrix + fracture case, in that you shouldn't need to "flatten" it any more.
