### ISSUE TITLE
Field initialization

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#456]
Consider the case when only one component of a composite vector has been initialized. Some PK must complete initialization of the other components. However, with a single flag initialized_, there is no way to separate this case from the case where all components were initialized. 

For this reason, flow PKs interpolate pressure data from cells to faces to get a reasonable estimate of the Darcy flux. However, this interpolation is approximate and is not needed when both components were already taken from an initialization file. 

Suggestion is to consider a vector of flags initialized_. Any thoughts?

**Comment by ecoon** [comment]
I've been bitten by similar issues on this.  I'm in favor of it as a concept.

I think we should have a bit of a discussion on initialization in general.  I think this is the thing that holds up general initialization order differences between Amanzi and ATS.  As I understand it, ATS initializes things in the PK.  The point of this is that the PK can do special things that know about physics.  It initializes things from a parameter list that is a sublist of that PK.  Amanzi on the other hand initializes things in State (I think?)  The list comes from the State list.  

The advantage of ATS's way is that the physics is self contained.  Any physics-specific initialization is known by the PK (eg. hydrostatic, etc) and all physics is in the evaluator or PK.  

The advantage of Amanzi's way is that it is a bit easier to deal with initialization dependencies (e.g. pressure from saturation, or chemistry initialization depending upon water saturation).  

I'm willing to be convinced to move ATS initialization into State, but I'd like to hear about how two issues are dealt with -- 1, where do you put physics-specific initialization (e.g. hydrostatic pressure)?  I hope this logic doesn't have to live somewhere special when it should really be flow-specific.  And 2, how do you orchestrate order?  For instance, in flow + reactive transport, where reactions need water saturation, but water saturation is consistent with pressure, how do you enforce that flow initializes first?  In PKs, that is easy because you have a PK tree that sets the order.  In State I'm not sure how that works.

**Comment by lipnikov** [comment]
In Amanzi, State begins and PK completes initialization of fields. PK knows physics and can correct deficiencies of a State initialization. For instance, high-level spec creates state sublist for initializing hydrostatic pressure. Then, Flow PK solves a saturated problem to correct the hydrostatic pressure. Both steps are optional. Saturation is updates by the Flow PK. 

The difference with ATS is that InitializeEvaluators() is called before PK's initialization. In ATS evaluators are initialized after PK. Since, we use the lazy evaluation strategy, this should not matter (I think).

**Comment by lipnikov** [comment]
vandeley "boundary face" will be addressed under a different ticket contingent to new ideas.
