### ISSUE TITLE
Travis-CI failed due to Docker's pull rate limit

### ISSUE THREAD

**Issue by ajkhattak** [amanzi/amanzi#525]
I am getting the following during Travis CI. Any idea?
From https://travis-ci.org/github/amanzi/amanzi/jobs/760995277:
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
The command "docker build --build-arg [secure]_branch=${TRAVIS_BRANCH} --build-arg [secure]_pr=${TRAVIS_PULL_REQUEST} --build-arg [secure]_tpls_ver=${AMANZI_TPLS_VER} -t ${DOCKER_USERNAME}/[secure]:${TRAVIS_BRANCH//\//--}-temp-build-stage-1 -f Dockerfile-Amanzi-build-stage-1 ." exited with 1.
0.50s$ echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
WARNING! Your password will be stored unencrypted in /home/travis/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
The command "echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin" exited with 0.
0.09s$ docker push $DOCKER_USERNAME/[secure]:${TRAVIS_BRANCH//\//--}-temp-build-stage-1
The push refers to repository [docker.io/[secure]/[secure]]
An image does not exist locally with the tag: [secure]/[secure]
The command "docker push $DOCKER_USERNAME/[secure]:${TRAVIS_BRANCH//\//--}-temp-build-stage-1" exited with 1.
Done. Your build exited with 1.

**Comment by lipnikov** [comment]
I made a simple commit to re-produce the problem.

**Comment by jd-moulton** [comment]
I don't quite understand what is happening between Travis CI and Dockerhub.  Specifically, at this point I don't see how these docker builds are hitting the rate limit, but it could be that the failure on the Travis CI side (seem to be lots of retries), is leading to too many requests being processed on the Dockerhub side (so our rate limit is hit).   

Since we are also having trouble with tests failing under Travis (likely due to resource limitations), it's likely our best best is to switch to GitHub actions.   I'll try to dig in when I have breaks this week, but since I'm away, it may be next week before I can wrap up a real fix.   Note you can restart the build and see if it passes this particular issue.

**Comment by ajkhattak** [comment]
Thanks @lipnikov and @jd-moulton. The first commit on my branch went pretty well until it caught a syntax error (missing comma), after fixing that I got this rate limit issue. However, after another commit it is going nicely without any issue so far; build phase 1 and 2 passed. 
Thanks David for the "restart" hint, I didn't know if there is such an option.
