### ISSUE TITLE
SuperLU  parsing libblas

### ISSUE THREAD

**Issue by ecoon** [amanzi/amanzi#556]
On ubuntu, I get the following error when building SuperLU in TPLs:

make[5]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libf77blas.so|/usr/lib/x86_64-linux-gnu/libatlas.so', needed by 'SRC/libsuperlu.so.5.2.2'.  Stop.

Staring at the configure script generated, it appears we pass in:

-DTPL_BLAS_LIBRARIES=/usr/lib/x86_64-linux-gnu/libblas.so|/usr/lib/x86_64-linux-gnu/libf77blas.so|/usr/lib/x86_64-linux-gnu/libatlas.so

It appears SuperLU does not correctly deal with more than one pipe maybe?  Note the target suggests SuperLU has split off the first one but not the second?

**Comment by ecoon** [comment]
20.04 

$ apt list --installed | grep atlas
libatlas-base-dev/focal,now 3.10.3-8ubuntu7 amd64 [installed]
libatlas3-base/focal,now 3.10.3-8ubuntu7 amd64 [installed,automatic]

Though this is from an ORNL managed repo center, so I suppose there could be some weird security things going on.

**Comment by ecoon** [comment]
I'm not sure what the pipe is there --- does it mean "or" or is it a substitution for ; because you would need escaped or quoted semicolons somewhere?

**Comment by ecoon** [comment]
Replacing the | by \\\;  (e.g. 3 slashes followed by a semicolon) seems to work.

**Comment by jd-moulton** [comment]
Great, I guess that makes sense -- escape the escape and escape the ;.   Are you going to push this update?

**Comment by jd-moulton** [comment]
I don't think the three backslashes works completely, looks like it adds semi-colons but without the escape and the escape doesn't seem to get the complete string loaded into CMake either.  So it only seems to use the first library in the list. It may seem to be working because in a shared build it may leave some symbols unresolved, or the ones you needed were in the first library.  I wonder if a more robust solution would be to put these things in a cache file.
