### ISSUE TITLE
multiple warnings/errors executing "make pdf"

### ISSUE THREAD

**Issue by lipnikov** [amanzi/amanzi#74]
Building documentation for input spec fails for "make pdf".

**Comment by jd-moulton** [comment]
Please let me know what system you are on OS, and what python distribution you are using.  Also, it would be helpful if you could provide the log showing the failure.

**Comment by lipnikov** [comment]
OS: serrano1
1st Error: ! Package inputenc Error: Unicode char \u8:��� not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1378 \theta_f���
                  =���\phi_f\, \eta_l\, s_{lf},\quad

**Comment by lipnikov** [comment]
2nd Error:
! LaTeX Error: Too deeply nested.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5834 \begin{itemize}

**Comment by jd-moulton** [comment]
The problem with the "Too deeply nested" list is harder to fix.  It is a current limitation of the DocUtils LaTeX writer, and on their ToDo list.  Although, recently a note was added that it has been fixed in 0.13.1.  So I will dig a little deeper and figure out where we stand with versions and behavior.

**Comment by lipnikov** [comment]
created PDF looks okay.
